### ISSUE TITLE
403 in Heroku deployment

### ISSUE THREAD

**Issue by noamelf** [FoundersAS/walkiebot#6] opened 2018-05-18 17:57 UTC
Hi,
First, thanks for your work, I realy enjoy working with walkie!

I deployed my app to heruko: https://walkiebot-learny.herokuapp.com/, and the deployment went well but I try to open the app, I get a blank screen. Looking at the dev tools console, I see that I receive a 403 error. 

Any advice?

**Comment by dinoshauer** [comment] 2018-05-22 09:43
Duplicate of #4

**Closed as completed by dinoshauer** 2018-05-22 09:43 UTC
